### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by andferrari** [radio-astro/simms#37]
Install fails with an error (on ubuntu). It seems related to `requirements.txt`.

thank-you for your help!

```
$ pip install simms
Collecting simms
  Using cached simms-0.9.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-zXr0QU/simms/setup.py", line 36, in <module>
        install_requires=requires(),
      File "/tmp/pip-build-zXr0QU/simms/setup.py", line 24, in requires
        with open(os.path.join('requirements.txt')) as f:
    IOError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ffhWKf/simms/
```

**Comment by SpheMakh** [comment]
Fixed in 075f41145dd4f945e1d47f6d4d0379a016e7aa77 
The latest release version (0.9.5) should work install.
