### ISSUE TITLE
Synthesis time wrong?

### ISSUE THREAD

**Issue by KshitijT** [radio-astro/simms#49]
While using simms:
```
simms --name "/home/kshitij/msdir/MeerKAT_X_shaped_sources_may_19_J1656+3952" --tel "meerkat" --type "casa" --coord-sys "itrf" --direction J2000,16h56m36.65s,+39d52m58.3s --synthesis 12.0 --scan-length 0.25 --dtime 16 --freq0 900MHz --dfreq 5MHz --nband 1 --nchan 300 --pol "XX XY YX YY" --feed "perfect X Y" --date "UTC,2019/05/01" --nolog
```
I get a total synthesis time of a single scan, rather than the full 12 hours integration time:
```
2019-01-11 13:48:04     INFO    NewMSSimulator::observe()+      Full time range: 01-May-2019/00:00:37.0 -- 01-May-2019/00:15:37.0 TAI with int = 16
```

**Comment by SpheMakh** [comment]
This went wrong in the previous commit. I just made a fix in branch issue-49, please test it

**Comment by KshitijT** [comment]
Thanks for the quick fix, @SpheMakh  !

Now it creates the proper range of time asked:
![image](https://user-images.githubusercontent.com/9251962/51072602-30a66100-166c-11e9-8d30-c7b392cea21f.png)
But I get this error:
```
2019-01-12 11:01:40	SEVERE	putcol::FLAG	Exception Reported: ArrayBase::Array(const IPosition&) - Negative shape shape [-2087124992] differs from [-2087124992]
Traceback (most recent call last):
  File "/casa-release-5.1.2-4.el7/lib/python2.7/init_welcome.py", line 24, in <module>
    execfile(__candidates[0])
  File "/tmp/tmpJmGXtM.py", line 6, in <module>
    makems(msname="/home/kshitij/msdir/MeerKAT_X_shaped_sources_may_19_J0838+3253", label="None", tel="meerkat", pos="/usr/local/lib/python2.7/dist-packages/simms/observatories/meerkat.itrf.txt", pos_type="ascii", synthesis=12, scan_length=['0.25'], dtime="16.0", freq0=['900MHz'], dfreq=['5MHz'], nchan=[300], stokes="XX XY YX YY", start_time=None, setlimits=False, elevation_limit=0.000000, shadow_limit=0.000000, coords="itrf",lon_lat="None", noup=False, nbands=1, direction=['J2000,08h38m44.61s,+32d53m11.8s'], outdir=".",date="UTC,2019/05/01",fromknown=False, feed="perfect X Y",scan_lag=0,auto_corr=False)
  File "/usr/local/lib/python2.7/dist-packages/simms/casasm.py", line 248, in makems
    tb.putcol("FLAG", flags)
  File "/casa-release-5.1.2-4.el7/lib/python2.7/__casac__/table.py", line 2363, in putcol
    return _table.table_putcol(self, columnname, value, startrow, nrow, rowincr)
RuntimeError: ArrayBase::Array(const IPosition&) - Negative shape shape [-2087124992] differs from [-2087124992]
```

**Comment by KshitijT** [comment]
Yup, fixed. Thanks !

**Comment by KshitijT** [comment]
After the update, if I try plotting, say, the uvcoverage with plotms, I get a message saying "all data are flagged", but the same works fine with plotuv (this was not the case earlier), does it have anything to do with the updates?

**Comment by SpheMakh** [comment]
Since you have specified the -date (but not the time) the observation will start at 00:00:00, and I suspect that the source is not up for the duration of the observation. Try out the new "--optimise-start" option which will modify the start time (-date) such that the source is visible for as long as possible
